wireplumber.components = [
  {
    name = audeze-maxwell-chat.lua, type = script/lua
    provides = custom.audeze-maxwell-chat
    requires = [ support.lua-scripting ]
  }
]

wireplumber.profiles = {
  main = {
    custom.audeze-maxwell-chat = required
  }
}

device.profile.priority.rules = [
  {
    matches = [
      {
        device.vendor.id = "0x3329"
        device.product.id = "0x4b19"
      }
    ]
    actions = {
      update-props = {
        priorities = ["output:analog-stereo+input:mono-fallback", "output:analog-stereo"]
      }
    }
  }
]

monitor.alsa.rules = [
  {
    matches = [
      {
        alsa.components = "USB3329:4b19"
        api.alsa.pcm.stream = "playback"
      }
    ]
    actions = {
      update-props = {
        node.description = "Audeze Maxwell Chat"
        node.nick        = "Audeze Maxwell Chat"
        node.name        = "alsa_output.audeze-maxwell-chat-acp"
      }
    }
  }
]
